name: Python CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mypy pytest pylint black

    - name: Lint with Pylint
      run: pylint src/

    - name: Typehint with Mypy
      run: mypy --ignore-missing-imports src/

    - name: Test with Pytest
      run: pytest tests/

    - name: Format code with Black
      run: black -l 79 *.py

    - name: Clean up
      run: |
        find . -type f -name "*.pyc" | xargs rm -fr
        find . -type d -name __pycache__ | xargs rm -fr
